server:
  port: 8001

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
  routes:
    user-service: /user-service/**
    device-service: /device-service/**
  ignored-services: '*'
  sensitiveHeaders: Cookie,Set-Cookie